project:
  type: website
  render:
  - "Phase 0 Pitch.qmd"
  - about.qmd
  - index.qmd
  - hello.qmd
  # - "Assignment-1-instructions.qmd"
  output-dir: docs

filters:
  - shinylive

website:
  title: "Data Visualization (CMSC 436 and 636) with Dr. Williams"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "floating"
    toggle: true
    search: true
    contents: auto

format:
  html:
    html-table-theme: striped
    html-table-bordered: true
    theme: [cosmo, brand]
    css: styles.css
    toc: true
    back-to-top-navigation: true
    crossrefs-hover: true 
    anchor-sections: true

